[project]
name = "test-circuit-synth-and-skidl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "circuit-synth>=0.12.1",
    "faiss-cpu>=1.13.2",
    "langchain>=1.2.10",
    "langchain-classic>=1.0.2",
    "langchain-ollama>=1.0.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "openrouter>=0.7.11",
    "pandas>=3.0.1",
    "pdfplumber>=0.11.9",
    "pyspice>=1.5",
    "reportlab>=4.4.9",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.2.3",
    "skidl>=2.2.1",
    "spyci>=1.0.2",
    "wget>=3.2",
]
